// <auto-generated />
using System;
using DogApp.Іnfrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogApp.Іnfrastructure.Migrations
{
    [DbContext(typeof(DogDbContext))]
    [Migration("20230605193720_CreatingDb")]
    partial class CreatingDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogApp.Domain.DbEntities.DbDog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<double>("TailLength")
                        .HasColumnType("float")
                        .HasColumnName("tail_length");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_dogs");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_dogs_name");

                    b.ToTable("dogs", null, t =>
                        {
                            t.HasCheckConstraint("ck_tail_length", "tail_length>=0 and tail_length<=100");

                            t.HasCheckConstraint("ck_weight", "weight>0 and weight<=150");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4783b6a-9c04-4d57-a010-3351c877dd6c"),
                            Color = "white",
                            Name = "Jeck",
                            TailLength = 10.0,
                            Weight = 20.5
                        },
                        new
                        {
                            Id = new Guid("1a20c33e-a3b8-4f8c-ace5-c1751f7de304"),
                            Color = "black",
                            Name = "Alice",
                            TailLength = 6.0,
                            Weight = 15.0
                        },
                        new
                        {
                            Id = new Guid("5193adb0-af3e-4610-9eeb-5c5133393012"),
                            Color = "black & brown",
                            Name = "Richard",
                            TailLength = 20.0,
                            Weight = 40.700000000000003
                        },
                        new
                        {
                            Id = new Guid("2c042acc-38bd-461d-a489-07ee786518da"),
                            Color = "brown & white",
                            Name = "Bob",
                            TailLength = 15.0,
                            Weight = 30.300000000000001
                        },
                        new
                        {
                            Id = new Guid("768677ef-648e-4a9b-b2dd-958792c3acac"),
                            Color = "grey",
                            Name = "Norman",
                            TailLength = 17.0,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("303bc3ba-fb9a-4404-8343-9612c89662a2"),
                            Color = "black",
                            Name = "David",
                            TailLength = 35.0,
                            Weight = 40.0
                        },
                        new
                        {
                            Id = new Guid("b2ad8106-01e4-4b27-9d7a-aeed1df3693c"),
                            Color = "brown",
                            Name = "Neo",
                            TailLength = 20.0,
                            Weight = 44.700000000000003
                        },
                        new
                        {
                            Id = new Guid("e2d1340f-3401-46e7-96ef-d1f2fe8c09a9"),
                            Color = "brown & white",
                            Name = "Jessy",
                            TailLength = 23.300000000000001,
                            Weight = 37.600000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
