// <auto-generated />
using System;
using DogApp.Іnfrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogApp.Іnfrastructure.Migrations
{
    [DbContext(typeof(DogDbContext))]
    partial class DogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogApp.Domain.DbEntities.DbDog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<double>("TailLength")
                        .HasColumnType("float")
                        .HasColumnName("tail_length");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_dogs");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_dogs_name");

                    b.ToTable("dogs", null, t =>
                        {
                            t.HasCheckConstraint("ck_tail_length", "tail_length>=0 and tail_length<=100");

                            t.HasCheckConstraint("ck_weight", "weight>0 and weight<=150");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("cbdf6c20-5512-4fa6-a809-aa2d18ef3177"),
                            Color = "white",
                            Name = "Jeck",
                            TailLength = 10.0,
                            Weight = 20.5
                        },
                        new
                        {
                            Id = new Guid("522c2af8-fa09-4a09-8688-ad82ce28e96d"),
                            Color = "black",
                            Name = "Alice",
                            TailLength = 6.0,
                            Weight = 15.0
                        },
                        new
                        {
                            Id = new Guid("8211c646-1be7-467b-8818-0333024ae862"),
                            Color = "black & brown",
                            Name = "Richard",
                            TailLength = 20.0,
                            Weight = 40.700000000000003
                        },
                        new
                        {
                            Id = new Guid("c61af73e-68fb-4b30-9e45-e3362ed4f378"),
                            Color = "brown & white",
                            Name = "Bob",
                            TailLength = 15.0,
                            Weight = 30.300000000000001
                        },
                        new
                        {
                            Id = new Guid("ab791748-e52f-4dd0-85ed-e981b09b92d2"),
                            Color = "grey",
                            Name = "Norman",
                            TailLength = 17.0,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("8f7b4b2e-1cad-4f59-bbc0-0d188146a65e"),
                            Color = "black",
                            Name = "David",
                            TailLength = 35.0,
                            Weight = 40.0
                        },
                        new
                        {
                            Id = new Guid("533df35a-8a05-4cc2-addd-584ed7bd9de6"),
                            Color = "brown",
                            Name = "Neo",
                            TailLength = 20.0,
                            Weight = 44.700000000000003
                        },
                        new
                        {
                            Id = new Guid("90069a2c-2363-4873-8c86-61b08663b1c1"),
                            Color = "brown & white",
                            Name = "Jessy",
                            TailLength = 23.300000000000001,
                            Weight = 37.600000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
